{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5.jar",
          "url": "spring-boot-loader-tools-3.0.5.jar",
          "size": 250651,
          "sha512": "72f2f94ae785c7f31502bfc49c6e30464d87f0ad984fe7009a84558a44189f0fadc930561e68f4a03c652ec3509b62182dcefdb476b344c8c0371697c2d8be92",
          "sha256": "f6e14bb944681c146a45595c1c88f40d08c49ef4c76366b902c00f36cf0ffc31",
          "sha1": "8d347283aaff1c6858a5dd4b25ff5c1db18d4791",
          "md5": "3af96610e9fb147cbf6d04e4bdc6ff0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5.jar",
          "url": "spring-boot-loader-tools-3.0.5.jar",
          "size": 250651,
          "sha512": "72f2f94ae785c7f31502bfc49c6e30464d87f0ad984fe7009a84558a44189f0fadc930561e68f4a03c652ec3509b62182dcefdb476b344c8c0371697c2d8be92",
          "sha256": "f6e14bb944681c146a45595c1c88f40d08c49ef4c76366b902c00f36cf0ffc31",
          "sha1": "8d347283aaff1c6858a5dd4b25ff5c1db18d4791",
          "md5": "3af96610e9fb147cbf6d04e4bdc6ff0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5-javadoc.jar",
          "url": "spring-boot-loader-tools-3.0.5-javadoc.jar",
          "size": 245785,
          "sha512": "b53a646a35debb294e8e00b2e6f176e4309b6db04608e29d3cac6a907a38a6de5fdd019450676ce92b66aa6434c06c41740ef11156880fd418e393db7fdb6d69",
          "sha256": "f816d5d63b951f91d7785edd7a7f1b405b5efe3bd2d037aa3d7b3856112931fa",
          "sha1": "47490805f3617f03095f7db8a038f0f4f8274b74",
          "md5": "71ed9316656881be741fde77d26da0eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5-sources.jar",
          "url": "spring-boot-loader-tools-3.0.5-sources.jar",
          "size": 73276,
          "sha512": "f52bf6cb442ec712fdfe5b88c479311d75aee8403244fd9a5bf3dd9882382d29961f6ff1394babe2b7485ce34afe626750e02154859f27e26f02020eb3e014fa",
          "sha256": "ddc18131d0ca14631eb3bb0e51ab8fa1877368c64d6a653edb56a93b10380346",
          "sha1": "4df8a6b9a46bf61772aec64fa03ca66870ea796d",
          "md5": "6e8e8d41e29c54a66ec1eb46fa658b7d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5.jar",
          "url": "spring-boot-loader-tools-3.0.5.jar",
          "size": 250651,
          "sha512": "72f2f94ae785c7f31502bfc49c6e30464d87f0ad984fe7009a84558a44189f0fadc930561e68f4a03c652ec3509b62182dcefdb476b344c8c0371697c2d8be92",
          "sha256": "f6e14bb944681c146a45595c1c88f40d08c49ef4c76366b902c00f36cf0ffc31",
          "sha1": "8d347283aaff1c6858a5dd4b25ff5c1db18d4791",
          "md5": "3af96610e9fb147cbf6d04e4bdc6ff0c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.5.jar",
          "url": "spring-boot-loader-tools-3.0.5.jar",
          "size": 250651,
          "sha512": "72f2f94ae785c7f31502bfc49c6e30464d87f0ad984fe7009a84558a44189f0fadc930561e68f4a03c652ec3509b62182dcefdb476b344c8c0371697c2d8be92",
          "sha256": "f6e14bb944681c146a45595c1c88f40d08c49ef4c76366b902c00f36cf0ffc31",
          "sha1": "8d347283aaff1c6858a5dd4b25ff5c1db18d4791",
          "md5": "3af96610e9fb147cbf6d04e4bdc6ff0c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.5"
        }
      ]
    }
  ]
}
