{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.0.7.jar",
          "url": "spring-web-6.0.7.jar",
          "size": 1754313,
          "sha512": "d13c2525214c96cda39ec15af8cb35360c8ef16262ecc682ff7b01dd1e550afc9c77ad07eee6e96f40e340f5a2c20b46ee6ae35261a7bf3b53c8c27c85950de8",
          "sha256": "740acb5f23ba39dcd8b075493f7e8672b0d21665a8d76867e05c0dd4fd4c1c7a",
          "sha1": "43f8ac9c46c15d57fca00fc81ce1f2849f6cecb9",
          "md5": "a6747c24284f2f04d091542277188477"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.0.7.jar",
          "url": "spring-web-6.0.7.jar",
          "size": 1754313,
          "sha512": "d13c2525214c96cda39ec15af8cb35360c8ef16262ecc682ff7b01dd1e550afc9c77ad07eee6e96f40e340f5a2c20b46ee6ae35261a7bf3b53c8c27c85950de8",
          "sha256": "740acb5f23ba39dcd8b075493f7e8672b0d21665a8d76867e05c0dd4fd4c1c7a",
          "sha1": "43f8ac9c46c15d57fca00fc81ce1f2849f6cecb9",
          "md5": "a6747c24284f2f04d091542277188477"
        }
      ]
    }
  ]
}
